"""
Base strategy interface for all trading strategies.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Optional


class Signal(Enum):
    """Trading signal types."""
    STRONG_BUY = "strong_buy"
    BUY = "buy"
    HOLD = "hold"
    SELL = "sell"
    STRONG_SELL = "strong_sell"


@dataclass
class TradeSignal:
    """A trading signal generated by a strategy."""
    signal: Signal
    confidence: float          # 0.0 to 1.0
    target_outcome: str        # "yes" or "no"
    suggested_size: float      # Suggested position size as fraction of max
    reason: str                # Human-readable explanation
    strategy_name: str         # Which strategy generated this

    @property
    def is_actionable(self) -> bool:
        return self.signal in (Signal.STRONG_BUY, Signal.BUY,
                               Signal.STRONG_SELL, Signal.SELL)

    @property
    def is_buy(self) -> bool:
        return self.signal in (Signal.STRONG_BUY, Signal.BUY)

    @property
    def is_sell(self) -> bool:
        return self.signal in (Signal.STRONG_SELL, Signal.SELL)


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    def __init__(self, name: str):
        self.name = name
        self.total_signals = 0
        self.profitable_signals = 0

    @abstractmethod
    def analyze(self, market, price_history: list[dict],
                order_book: dict) -> Optional[TradeSignal]:
        """
        Analyze a market and return a trading signal.

        Args:
            market: Market object with current prices
            price_history: List of historical price points
            order_book: Current order book data

        Returns:
            TradeSignal if there's a trading opportunity, None otherwise
        """
        pass

    @property
    def win_rate(self) -> float:
        if self.total_signals == 0:
            return 0.0
        return self.profitable_signals / self.total_signals

    def record_result(self, profitable: bool):
        """Record the result of a signal."""
        self.total_signals += 1
        if profitable:
            self.profitable_signals += 1
